spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/obsidiana_dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    com.nexcoyo.knowledge.obsidiana: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
