server:
  port: ${PORT:8080}

spring:
  application:
    name: Obsidiana
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
          fetch_size: 100
        default_schema: public

  flyway:
    enabled: true

  main:
    log-startup-info: false

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

app:
  security:
    jwt:
      issuer: "obsidian-api"
      secret: "${JWT_SECRET}"
      accessTokenMinutes: 15
    refresh:
      days: 14
    resetPassword:
      tokenMinutes: 30
    max-sessions: 2
